#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__)) + '/../../config/boot'
rails_root = File.expand_path RAILS_ROOT
Dir.chdir(rails_root) # Change current directory to RAILS_ROOT
ENV['RAILS_ENV'] ||= "production"

require 'rubygems'
require "daemons"
require 'lib/daemons_extension'
require 'yaml'
require 'erb'

rails_version = File.new(rails_root + "/config/environment.rb").read.scan(/^ *RAILS_GEM_VERSION.*=.*['|"](.*)['|"]/)[0].to_s

gem 'activesupport', rails_version
require 'active_support'

options = YAML.load(
  ERB.new(
  IO.read(
  rails_root + "/config/daemons.yml"
  )).result).with_indifferent_access
options[:dir_mode] = options[:dir_mode].to_sym
options[:force_kill_wait] = 30

Daemons.run rails_root + '/lib/daemons/<%=file_name%>.rb', options
